server:
  port: 9760

spring:
  profiles:
    active: test #pre, prod
  main:
    web-application-type: servlet

#config:
#  test:
#    beanValue1: 1

logging:
  path: playground.log
  file:
    max-size: 10MB
  level:
    root: info
    com.slim.playground: warn
  config: classpath:logback-config.xml


